### ISSUE TITLE
support 256 colors

### ISSUE THREAD

**Issue by ohac** [jugyo/termcolor#1]
256色のサポートをしたいのですが、どんなタグがいいか考え中です。
http://www.frexx.de/xterm-256-notes/

案:
foreground f000 〜 f666
background b000 〜 b666
gray foreground f0 〜 f23
gray background b0 〜 b23

**Comment by jugyo** [comment]
いいんじゃないでしょうか :)
コミット権つけとくので、いじってもらって良いですよ

**Comment by ohac** [comment]
コミットしました。
9d8f032505182ac46b4c119e17fbb193b0761a79
